sonar.projectKey=aws-lambda-devkit
sonar.projectName=aws-lambda-devkit
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,templates/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
